// Mock data for SmartBite application

export const mockUsers = [
  {
    userId: "1",
    roleId: "1",
    roleName: "user",
    userName: "Phyu Khaing",
    userEmail: "pkk1@gmail.com",
    userPassword: "P@ssw0rd",
    userProfile: "https://api.dicebear.com/7.x/avataaars/svg?seed=pkk1",
    userPhNo: "+959123456789",
    latitude: 16.8409,
    longitude: 96.1735,
  },
  {
    userId: "2",
    roleId: "2",
    roleName: "admin",
    userName: "Admin User",
    userEmail: "pkk2@gmail.com",
    userPassword: "P@ssw0rd",
    userProfile: "https://api.dicebear.com/7.x/avataaars/svg?seed=pkk2",
    userPhNo: "+959123456790",
    latitude: 16.8409,
    longitude: 96.1735,
  },
  {
    userId: "3",
    roleId: "3",
    roleName: "delivery",
    userName: "Delivery Person",
    userEmail: "pkk3@gmail.com",
    userPassword: "P@ssw0rd",
    userProfile: "https://api.dicebear.com/7.x/avataaars/svg?seed=pkk3",
    userPhNo: "+959123456791",
    latitude: 16.8409,
    longitude: 96.1735,
  },
];

export const mockCategories = [
  { catId: "1", catName: "Burgers", activeFlag: true },
  { catId: "2", catName: "Pizza", activeFlag: true },
  { catId: "3", catName: "Asian Cuisine", activeFlag: true },
  { catId: "4", catName: "Desserts", activeFlag: true },
  { catId: "5", catName: "Beverages", activeFlag: true },
];

export const mockFoods = [
  {
    foodId: "1",
    catId: "1",
    catName: "Burgers",
    name: "Classic Beef Burger",
    eachPrice: 8500,
    cost: 4000,
    profit: 4500,
    cookingTime: 15,
    foodImage: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    foodDescription: "Juicy beef patty with fresh lettuce, tomato, and our special sauce",
    activeFlag: true,
    otherTopics: ["Cheese", "Bacon", "Extra Patty"],
  },
  {
    foodId: "2",
    catId: "2",
    catName: "Pizza",
    name: "Margherita Pizza",
    eachPrice: 12000,
    cost: 5500,
    profit: 6500,
    cookingTime: 20,
    foodImage: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
    foodDescription: "Classic Italian pizza with fresh mozzarella and basil",
    activeFlag: true,
    otherTopics: ["Extra Cheese", "Olives", "Mushrooms"],
  },
  {
    foodId: "3",
    catId: "3",
    catName: "Asian Cuisine",
    name: "Pad Thai",
    eachPrice: 7500,
    cost: 3500,
    profit: 4000,
    cookingTime: 12,
    foodImage: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=400",
    foodDescription: "Traditional Thai stir-fried noodles with peanuts and lime",
    activeFlag: true,
    otherTopics: ["Extra Shrimp", "Spicy", "Vegetarian"],
  },
  {
    foodId: "4",
    catId: "1",
    catName: "Burgers",
    name: "Chicken Deluxe",
    eachPrice: 7800,
    cost: 3800,
    profit: 4000,
    cookingTime: 15,
    foodImage: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400",
    foodDescription: "Crispy chicken breast with mayo and pickles",
    activeFlag: true,
    otherTopics: ["Cheese", "Spicy Mayo", "Extra Crispy"],
  },
  {
    foodId: "5",
    catId: "4",
    catName: "Desserts",
    name: "Chocolate Lava Cake",
    eachPrice: 5500,
    cost: 2500,
    profit: 3000,
    cookingTime: 8,
    foodImage: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400",
    foodDescription: "Warm chocolate cake with molten center, served with vanilla ice cream",
    activeFlag: true,
    otherTopics: ["Extra Ice Cream", "Whipped Cream", "Berries"],
  },
  {
    foodId: "6",
    catId: "5",
    catName: "Beverages",
    name: "Mango Smoothie",
    eachPrice: 3500,
    cost: 1500,
    profit: 2000,
    cookingTime: 5,
    foodImage: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400",
    foodDescription: "Fresh mango blended with yogurt and ice",
    activeFlag: true,
    otherTopics: ["Extra Mango", "Less Sugar", "Add Protein"],
  },
];

export const mockTowns = [
  { townId: "1", townName: "Yangon Downtown", centerLatitude: 16.8409, centerLongitude: 96.1735, radiusKm: 5 },
  { townId: "2", townName: "Mandalay Center", centerLatitude: 21.9588, centerLongitude: 96.0891, radiusKm: 5 },
  { townId: "3", townName: "Naypyidaw", centerLatitude: 19.7633, centerLongitude: 96.0785, radiusKm: 8 },
];

export const mockStores = [
  {
    storeId: "1",
    townId: "1",
    townName: "Yangon Downtown",
    storePlace: "Corner of Bogyoke St",
    storeName: "SmartBite Central Kitchen",
    storePhNo: "+959401234567",
    storeLatitude: 16.8409,
    storeLongitude: 96.1735,
    activeFlag: true,
  },
  {
    storeId: "2",
    townId: "2",
    townName: "Mandalay Center",
    storePlace: "84th Street",
    storeName: "SmartBite Mandalay",
    storePhNo: "+959401234568",
    storeLatitude: 21.9588,
    storeLongitude: 96.0891,
    activeFlag: true,
  },
];

export const mockOrders = [
  {
    orderId: "1",
    userId: "1",
    userName: "Phyu Khaing",
    storeId: "1",
    storeName: "SmartBite Central Kitchen",
    townId: "1",
    townName: "Yangon Downtown",
    deliveryId: "3",
    deliveryName: "Delivery Person",
    paymentId: "1",
    paymentType: "Cash on Delivery",
    totalPrice: 16000,
    totalCost: 7500,
    totalProfit: 8500,
    orderDate: new Date("2025-01-15"),
    orderingPlace: "Sanchaung Township",
    orderLatitude: 16.8209,
    orderLongitude: 96.1435,
    status: "Delivered",
    orderDescription: "Please ring the doorbell twice",
    estimatedDeliveryTime: 30,
    deliveryStarted: new Date("2025-01-15T12:30:00"),
    deliveredTime: new Date("2025-01-15T12:55:00"),
    items: [
      {
        foodId: "1",
        name: "Classic Beef Burger",
        eachPrice: 8500,
        quantity: 1,
        cookingTime: 15,
        foodImage: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
        foodDescription: "Juicy beef patty with fresh lettuce, tomato, and our special sauce",
        catName: "Burgers",
        otherTopics: ["Cheese", "Bacon"],
      },
      {
        foodId: "3",
        name: "Pad Thai",
        eachPrice: 7500,
        quantity: 1,
        cookingTime: 12,
        foodImage: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=400",
        foodDescription: "Traditional Thai stir-fried noodles with peanuts and lime",
        catName: "Asian Cuisine",
        otherTopics: ["Extra Shrimp"],
      },
    ],
  },
  {
    orderId: "2",
    userId: "1",
    userName: "Phyu Khaing",
    storeId: "1",
    storeName: "SmartBite Central Kitchen",
    townId: "1",
    townName: "Yangon Downtown",
    deliveryId: "3",
    deliveryName: "Delivery Person",
    paymentId: "2",
    paymentType: "Online Payment",
    totalPrice: 12000,
    totalCost: 5500,
    totalProfit: 6500,
    orderDate: new Date(),
    orderingPlace: "Sanchaung Township",
    orderLatitude: 16.8209,
    orderLongitude: 96.1435,
    status: "In Progress",
    orderDescription: "Leave at the door",
    estimatedDeliveryTime: 25,
    deliveryStarted: new Date(),
    items: [
      {
        foodId: "2",
        name: "Margherita Pizza",
        eachPrice: 12000,
        quantity: 1,
        cookingTime: 20,
        foodImage: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
        foodDescription: "Classic Italian pizza with fresh mozzarella and basil",
        catName: "Pizza",
        otherTopics: ["Extra Cheese"],
      },
    ],
  },
];

export const mockCart = [
  {
    cartId: "1",
    userId: "1",
    foodId: "1",
    quantity: 2,
    food: mockFoods[0],
    selectedTopics: ["Cheese", "Bacon"],
  },
];

export const mockFavorites = [
  {
    favoriteId: "1",
    userId: "1",
    foodId: "1",
    food: mockFoods[0],
  },
  {
    favoriteId: "2",
    userId: "1",
    foodId: "5",
    food: mockFoods[4],
  },
];

export const mockRoles = [
  { roleId: "1", roleName: "user", activeFlag: true },
  { roleId: "2", roleName: "admin", activeFlag: true },
  { roleId: "3", roleName: "delivery", activeFlag: true },
];

export const mockDeliveries = [
  {
    deliveryId: "3",
    name: "Delivery Person",
    email: "pkk3@gmail.com",
    phNo: "+959123456791",
    townId: "1",
    townName: "Yangon Downtown",
    currentLatitude: 16.8409,
    currentLongitude: 96.1735,
    isOnline: true,
    activeFlag: true,
  },
];
